language: node_js
node_js:
- lts/carbon
after_success:
- npm run build # Maak een dist folder
cache:
  directories:
  - node_modules
before_install: 
before_deploy:
  - cd dist/ng-kaart # Naar dist gaan zodat de publish van daaruit gebeurt
deploy:
  provider: npm
  email: geert.subcribe1+npm@gmail.com
  api_key:
    secure: axk0wuGoTqhyICGL91mwInYiCrIiMtBZxYqMqKUHPr2J8oN6/D1DlvGIktvPT4lwMRa8PMrPtO2uDpeO5i7FErc/qgKU0tlUeWp5jLGzfpKsPJx6Jyu75oHKDb8wnufSbxWNsmkn6l7P7cDYym2K2/iXJc7i3UTdmZ+dymxFHmi2uLUmI4SfORxgNDCqwM8AyXnsBjHhPgWEFOfqTkI7is04Dy8g1V6TA+CXlLTp76EBZrcxEPAyRFJjiEJgIp/DqYpFJhwBwOY0cE+aSCTzNK0ZIyYVVEPs63HLgjR7LZ9Mmx37HiKQQ16hLppBAl3vCXHQaEt/fV0FMYrhFkM7XKAEr/qHiZwvqGuinszh2yi00gYQU0IO753djOhWWjEO5GMrXnFLHIb7RyTaV5LhY4Es1Ndv+ezAye3PxkufOODCNkkJh6Iv0Bmg9oJGlge/z+Yj+6rsFhJOF+66Yid4O8GctuTKXgEOcrfJCcdld4HQbmXsnOhdZZnspLpkDM0BeyMtac8Q2GXAOw5DO7got2D+CvOHImx4yNSJ82qo8S8tCCkz65HHolXHFohG06ofBEVpIFg4+agvtQKHNKQ3CqE9L1P/PkWbocWgKbVYXkxZUbHaWgGlU1hOm0xEioUOA8kZmLTYMBE6JLZIsJttWbAr3AVDW95blts/jx6+Sr8=
  skip_cleanup: true # dist niet weg gooien
  on:
    tags: true 
    branch: master
notifications:
  hipchat:
    rooms:
      secure: Y3ktCQtIz6GB3jopjAJSMD52I7qBMQaQojQtmXleSlWuQjbyU8mQSewF4uh0cAVrAybFEK+1OzH0kKYwIvqJk6hcw8lG7QR7e5xm3DuuMrsbDbT5/us9P1A0lw61UMr+TaWneKyZAfNBuBeysdqTOaYyuh7bZlC4jNoWfZxRitKv9jPzs61yZjVTXMkmQ471UO/yiE8FVnNk8Uh6IxUz0LyXOyeansTvYDNldCvIjqJ+bConOdRJleOzitQ2b5OdN91OzC+3Xjd9e+9MzWAkOPNmwOen3CKfcFSEA0sdpC1RZGzyU9cB2+a2VwwGPMoCOXWC8TrhH9P8Rn8VYwhtu4dSD00xzy17/NRO0x4PNLoDMKNhrWtl5bUud4cO4qSkYmXV3+21RZ4/UganxaMYNS59wqfoqGMiCAupoxki4ZUvyEAcgwRSRQaw+eSHQQ2UNmWR5MLhxV9zKcL/uwsCGy+XM0NgJED/U2HPDHJsH9orN2/8G2nk7W700LYr3MYMfEcV/HWHieT8WKyg0Cc/971twKQnJaS5mgyE1dHgPyVmMXLYm5ZGTNbpOyxC/8fhj2Hc/YAeyNAZ8TlRahqXhYPJKFHV/haS/tlIN4/5aVxVfOoO+sHR1WJHMX+3wn+v+b3q7Hmt6bqF3HJJ993U502PQsE/gEDTkrQoWHLIlu4=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
sudo: required
addons:
  chrome: stable
script:
  - npm run test
  - npm run e2e
